# Generated by Django 4.1.1 on 2025-01-14 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('urunmodelleri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('ad', models.CharField(blank=True, max_length=40, null=True)),
                ('soyad', models.CharField(blank=True, max_length=40, null=True)),
                ('tckn', models.PositiveIntegerField(blank=True, default=11111111111, null=True)),
                ('onay', models.BooleanField(default=False)),
                ('bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('olusturma_zamani', models.DateTimeField(auto_now_add=True)),
                ('giris_zamani', models.DateTimeField(default=django.utils.timezone.now)),
                ('guncelleme_zamani', models.DateTimeField(auto_now=True)),
                ('profil_resmi', models.FileField(blank=True, null=True, upload_to='profilImage')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_magza', models.BooleanField(default=False)),
                ('is_systemuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunmodelleri.urunler')),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('adress', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAdres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
