# Generated by Django 4.1.1 on 2025-01-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankaAdi', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Magzalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mAdi', models.CharField(max_length=255)),
                ('mTelefon', models.CharField(max_length=15)),
                ('mAdresIl', models.CharField(max_length=30)),
                ('mAdresIlce', models.CharField(max_length=50)),
                ('mAdres', models.TextField()),
                ('mEmail', models.EmailField(max_length=255, unique=True)),
                ('mLogo', models.FileField(blank=True, null=True, upload_to='magzaLogo')),
                ('mWebAdres', models.CharField(max_length=255)),
                ('mVn', models.CharField(max_length=15)),
                ('mVd', models.CharField(max_length=250)),
                ('mBakiye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MCommet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mYorum', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MPuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mPuan', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SistemBakiye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sBakiye', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('gelenMagza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='magza.magzalar')),
            ],
        ),
    ]
