# Generated by Django 4.1.1 on 2025-01-14 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magza', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magzalar',
            name='guncelleme_zamani',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='magzalar',
            name='olusturma_zamani',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
