# Generated by Django 4.1.1 on 2025-01-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magza', '0004_alter_magzalar_puan'),
    ]

    operations = [
        migrations.AddField(
            model_name='magzalar',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='magza.mcommet'),
        ),
    ]
