# Generated by Django 4.1.1 on 2025-01-15 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magza', '0006_remove_magzalar_comment_remove_magzalar_puan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpuan',
            name='magza',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magza.magzalar'),
        ),
    ]
