# Generated by Django 4.1.1 on 2025-01-15 17:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magza', '0009_alter_mpuan_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mpuan',
            unique_together={('owner', 'magza')},
        ),
    ]
