# Generated by Django 4.1.1 on 2025-01-14 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urunmodelleri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upuan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sepeturunleri',
            name='sepet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sepetUrunleri', to='urunmodelleri.sepet'),
        ),
        migrations.AddField(
            model_name='sepeturunleri',
            name='urun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunmodelleri.urunler'),
        ),
        migrations.AddField(
            model_name='sepet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sepet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kargotakip',
            name='urun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='urunmodelleri.urunler'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
