# Generated by Django 4.1.1 on 2025-01-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunmodelleri', '0003_rename_yorum_comment_uyorum_remove_urunler_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet',
            name='is_complated',
            field=models.BooleanField(default=False),
        ),
    ]
